"""AMD IP-first architecture contracts."""

from .types import (
    ArchitectureBlockSpec,
    ArchitectureStatus,
    ConnectionStatus,
    HardwareArchitectureConfig,
    ImplementationKind,
    IntegrationProofStatus,
    IpFamilySpec,
    IpInstanceLifecycle,
    IpInstanceSpec,
    ParameterStatus,
    RFDC_2_6_VLNV,
    RequiredResponsibilitiesSpec,
    RfdcIntegrationMetadata,
)
from .evidence import (
    CatalogEvidence,
    CatalogResolutionStatus,
    ValidatedCatalogEvidence,
    build_candidate_lock,
    build_catalog_request,
    canonical_json_bytes,
    parse_catalog_evidence,
    validate_catalog_evidence,
)

__all__ = [
    "ArchitectureBlockSpec",
    "ArchitectureStatus",
    "ConnectionStatus",
    "CatalogEvidence",
    "CatalogResolutionStatus",
    "HardwareArchitectureConfig",
    "ImplementationKind",
    "IntegrationProofStatus",
    "IpFamilySpec",
    "IpInstanceLifecycle",
    "IpInstanceSpec",
    "ParameterStatus",
    "RFDC_2_6_VLNV",
    "RequiredResponsibilitiesSpec",
    "RfdcIntegrationMetadata",
    "ValidatedCatalogEvidence",
    "build_candidate_lock",
    "build_catalog_request",
    "canonical_json_bytes",
    "parse_catalog_evidence",
    "validate_catalog_evidence",
]
